/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProspectionRouteImport } from './routes/prospection'
import { Route as AppelsOffresIndexRouteImport } from './routes/appels-offres/index'
import { Route as AppelsOffresAoIdRouteImport } from './routes/appels-offres/$aoId'
import { Route as CataloguesIndexRouteImport } from './routes/catalogues/index'
import { Route as CataloguesCatalogueIdRouteImport } from './routes/catalogues/$catalogueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionRoute = ProspectionRouteImport.update({
  id: '/prospection',
  path: '/prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresIndexRoute = AppelsOffresIndexRouteImport.update({
  id: '/appels-offres/',
  path: '/appels-offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresAoIdRoute = AppelsOffresAoIdRouteImport.update({
  id: '/appels-offres/$aoId',
  path: '/appels-offres/$aoId',
  getParentRoute: () => rootRouteImport,
} as any)
const CataloguesIndexRoute = CataloguesIndexRouteImport.update({
  id: '/catalogues/',
  path: '/catalogues/',
  getParentRoute: () => rootRouteImport,
} as any)
const CataloguesCatalogueIdRoute = CataloguesCatalogueIdRouteImport.update({
  id: '/catalogues/$catalogueId',
  path: '/catalogues/$catalogueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/prospection': typeof ProspectionRoute
  '/appels-offres/$aoId': typeof AppelsOffresAoIdRoute
  '/catalogues/$catalogueId': typeof CataloguesCatalogueIdRoute
  '/appels-offres/': typeof AppelsOffresIndexRoute
  '/catalogues/': typeof CataloguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/prospection': typeof ProspectionRoute
  '/appels-offres/$aoId': typeof AppelsOffresAoIdRoute
  '/catalogues/$catalogueId': typeof CataloguesCatalogueIdRoute
  '/appels-offres': typeof AppelsOffresIndexRoute
  '/catalogues': typeof CataloguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/prospection': typeof ProspectionRoute
  '/appels-offres/$aoId': typeof AppelsOffresAoIdRoute
  '/catalogues/$catalogueId': typeof CataloguesCatalogueIdRoute
  '/appels-offres/': typeof AppelsOffresIndexRoute
  '/catalogues/': typeof CataloguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fournisseurs'
    | '/login'
    | '/profil'
    | '/prospection'
    | '/appels-offres/$aoId'
    | '/catalogues/$catalogueId'
    | '/appels-offres/'
    | '/catalogues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/fournisseurs'
    | '/login'
    | '/profil'
    | '/prospection'
    | '/appels-offres/$aoId'
    | '/catalogues/$catalogueId'
    | '/appels-offres'
    | '/catalogues'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/fournisseurs'
    | '/login'
    | '/profil'
    | '/prospection'
    | '/appels-offres/$aoId'
    | '/catalogues/$catalogueId'
    | '/appels-offres/'
    | '/catalogues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FournisseursRoute: typeof FournisseursRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  ProspectionRoute: typeof ProspectionRoute
  AppelsOffresAoIdRoute: typeof AppelsOffresAoIdRoute
  CataloguesCatalogueIdRoute: typeof CataloguesCatalogueIdRoute
  AppelsOffresIndexRoute: typeof AppelsOffresIndexRoute
  CataloguesIndexRoute: typeof CataloguesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection': {
      id: '/prospection'
      path: '/prospection'
      fullPath: '/prospection'
      preLoaderRoute: typeof ProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres/': {
      id: '/appels-offres/'
      path: '/appels-offres'
      fullPath: '/appels-offres/'
      preLoaderRoute: typeof AppelsOffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres/$aoId': {
      id: '/appels-offres/$aoId'
      path: '/appels-offres/$aoId'
      fullPath: '/appels-offres/$aoId'
      preLoaderRoute: typeof AppelsOffresAoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogues/': {
      id: '/catalogues/'
      path: '/catalogues'
      fullPath: '/catalogues/'
      preLoaderRoute: typeof CataloguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogues/$catalogueId': {
      id: '/catalogues/$catalogueId'
      path: '/catalogues/$catalogueId'
      fullPath: '/catalogues/$catalogueId'
      preLoaderRoute: typeof CataloguesCatalogueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FournisseursRoute: FournisseursRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  ProspectionRoute: ProspectionRoute,
  AppelsOffresAoIdRoute: AppelsOffresAoIdRoute,
  CataloguesCatalogueIdRoute: CataloguesCatalogueIdRoute,
  AppelsOffresIndexRoute: AppelsOffresIndexRoute,
  CataloguesIndexRoute: CataloguesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
