/** Auto-generated by scripts/import-prospection-csv.ts */
export const PROSPECTION_PRESTATAIRE_NOMENCLATURE: string[] = [
  "50 ANS EN YVELINES",
  "AGGLO GERGY PONTOISE CYLUMINE",
  "ALPHA TP",
  "ALTI ELECT",
  "Bentin",
  "Bir",
  "Bouygues",
  "Citeos",
  "COOPERATIVE ELECTRICITE VILLIERS (CEV)",
  "dalkaia",
  "DALKIA",
  "Dalkia Electronics",
  "Dalkia electrotechnics",
  "Derichebourg",
  "DERICHEBOURG",
  "DERICHEBOURG ENERGIE EP",
  "DEURICHEBOURG",
  "EDEF GRDF",
  "EDF",
  "EES",
  "ELEC3D",
  "ELEC3D SANS CONTRAT",
  "Enedis",
  "Entra",
  "EQUANS",
  "ERIMARCHER",
  "EXPERTITÉ",
  "GPSEO",
  "Help",
  "IMMOBAT",
  "INEDIS",
  "Inéo",
  "KOMPASS",
  "laissé un mail",
  "M Light",
  "MGPE",
  "N.C",
  "ne veulent pas donner",
  "NON COMMUNIQUÉ",
  "Pas de contrat (prefere gerer seul)",
  "perideral",
  "PF Lighting",
  "Pruneveille",
  "Prunevieille",
  "PRUNEVIEILLE",
  "PS LIGHTING",
  "Queckenborn",
  "QUEKENBORN",
  "Raoult",
  "Satelec",
  "SAUR",
  "SDAL",
  "SDEL IDF TRAVAUX",
  "SDESM",
  "SEET (syndicat des electriques de tarentaise)",
  "Seip",
  "services",
  "Services du groupe Equans",
  "Ses",
  "SFE Aubergenville",
  "Sicae",
  "SIE-ELY",
  "SIELY",
  "SIER",
  "SOBECA",
  "SOCIETE ENERGIES SERVICES À HOUDAN (78)",
  "Societe SOBECA",
  "SOMELEC",
  "Spie",
  "STELEC",
  "Stelens",
  "Stpee",
  "SYNDICAT : LE SIER DE CLAYE SOUINNY",
  "Terideal",
  "TERRE IDEAL",
  "Total energie",
  "Total Energie",
  "TOTAL ENERGIE",
  "un renouvellement est en cours",
  "VIALUM",
  "VIANUM",
  "Viola",
  "WATELET"
];

export const PROSPECTION_PRESTATAIRE_ALIASES: Record<string, string[]> = {
  "Citeos": [
    "citeos",
    "citéos",
    "spir city network",
    "cu gpseo"
  ],
  "EES": [
    "ees",
    "eiffage",
    "eiffage energie",
    "eiffage énergie",
    "eiffage energies",
    "eiffage energie + satelec",
    "eiffage energie + satelec"
  ],
  "Satelec": [
    "satelec"
  ],
  "Bouygues": [
    "bouygues",
    "bouygues energie",
    "bouygues energies et services",
    "bouygues energies et services / citeos"
  ],
  "Spie": [
    "spie",
    "spie citynetworks",
    "spie city networks"
  ],
  "Entra": [
    "entra"
  ],
  "Bir": [
    "bir"
  ],
  "GPSEO": [
    "gpseo"
  ],
  "SDESM": [
    "sdesm"
  ],
  "Enedis": [
    "enedis"
  ],
  "Pruneveille": [
    "pruneveille"
  ],
  "Inéo": [
    "ineo",
    "inéo"
  ],
  "EDF": [
    "edf"
  ],
  "Viola": [
    "viola"
  ],
  "Bentin": [
    "bentin"
  ],
  "Stelens": [
    "stelens"
  ],
  "M Light": [
    "m light",
    "mlight"
  ],
  "Queckenborn": [
    "queckenborn"
  ],
  "Seip": [
    "seip"
  ],
  "Ses": [
    "ses"
  ],
  "PF Lighting": [
    "pf lighting"
  ],
  "Raoult": [
    "raoult"
  ],
  "Terideal": [
    "terideal"
  ],
  "Sicae": [
    "sicae"
  ],
  "Stpee": [
    "stpee"
  ],
  "Help": [
    "help"
  ]
};
